services:
  akademik-db: # Nama service diubah sesuai spesifikasi Minggu 3
    image: postgres:17 
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: siakad
    ports: 
      - "5433:5432" 
    volumes:
      - dbdata:/var/lib/postgresql/data 
      - ./migrations:/docker-entrypoint-initdb.d 
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d siakad"]
      interval: 5s
      timeout: 5s
      retries: 5

  akademik-service:
    build: 
      context: ./akademik-service
      dockerfile: Dockerfile
    ports:
      - "8081:8080" # Port publikasi 8081, internal 8080
    environment:
      - DB_HOST=akademik-db 
      - DB_PORT=5432
      - DB_USER=postgres
      - DB_PASSWORD=postgres 
      - DB_NAME=siakad
      - DB_SSLMODE=disable
      - APP_PORT=8080
    depends_on:
      akademik-db:
        condition: service_healthy
  
  rekap-service:
    build: 
      context: ./rekap-service
      dockerfile: Dockerfile
    ports:
      - "8082:8080"
    environment:
      - APP_PORT=8080
      - AKADEMIK_BASE_URL=http://akademik-service:8080
    depends_on:
      - akademik-service

volumes:
  dbdata: 